// Generated by gencpp from file Tyrell/demo_srv.msg
// DO NOT EDIT!


#ifndef TYRELL_MESSAGE_DEMO_SRV_H
#define TYRELL_MESSAGE_DEMO_SRV_H

#include <ros/service_traits.h>


#include <Tyrell/demo_srvRequest.h>
#include <Tyrell/demo_srvResponse.h>


namespace Tyrell
{

struct demo_srv
{

typedef demo_srvRequest Request;
typedef demo_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct demo_srv
} // namespace Tyrell


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Tyrell::demo_srv > {
  static const char* value()
  {
    return "e21fb7853ad73d6d988d6371d4fed1e2";
  }

  static const char* value(const ::Tyrell::demo_srv&) { return value(); }
};

template<>
struct DataType< ::Tyrell::demo_srv > {
  static const char* value()
  {
    return "Tyrell/demo_srv";
  }

  static const char* value(const ::Tyrell::demo_srv&) { return value(); }
};


// service_traits::MD5Sum< ::Tyrell::demo_srvRequest> should match 
// service_traits::MD5Sum< ::Tyrell::demo_srv > 
template<>
struct MD5Sum< ::Tyrell::demo_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Tyrell::demo_srv >::value();
  }
  static const char* value(const ::Tyrell::demo_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Tyrell::demo_srvRequest> should match 
// service_traits::DataType< ::Tyrell::demo_srv > 
template<>
struct DataType< ::Tyrell::demo_srvRequest>
{
  static const char* value()
  {
    return DataType< ::Tyrell::demo_srv >::value();
  }
  static const char* value(const ::Tyrell::demo_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Tyrell::demo_srvResponse> should match 
// service_traits::MD5Sum< ::Tyrell::demo_srv > 
template<>
struct MD5Sum< ::Tyrell::demo_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Tyrell::demo_srv >::value();
  }
  static const char* value(const ::Tyrell::demo_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Tyrell::demo_srvResponse> should match 
// service_traits::DataType< ::Tyrell::demo_srv > 
template<>
struct DataType< ::Tyrell::demo_srvResponse>
{
  static const char* value()
  {
    return DataType< ::Tyrell::demo_srv >::value();
  }
  static const char* value(const ::Tyrell::demo_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TYRELL_MESSAGE_DEMO_SRV_H
